SEED: 11715851
MODEL:
  META_ARCHITECTURE: "BlendMask"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
    FREEZE_AT: 4
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
    MIN_SIZE: 8
  BASIS_MODULE:
    LOSS_ON: True
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False
  FCOS:
    THRESH_WITH_CTR: True
    NMS_TH: 0.3
    USE_SCALE: False
DATASETS:
    TRAIN: ("coco_train",)  # 自定义训练集名称
    TEST: ("coco_val",)      # 自定义验证集名称
SOLVER:
    IMS_PER_BATCH: 4
    BASE_LR: 0.01
    WEIGHT_DECAY: 0.0001
    MOMENTUM: 0.9
    STEPS: (60000, 80000)
    GAMMA: 0.1
    WARMUP_ITERS: 1000
    MAX_ITER: 2000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

